name: carp_background_location
description: A location plugin that works in the background. Supports Android and iOS
publish_to: 'none'
version: 3.0.2
homepage: https://github.com/cph-cachet/flutter-plugins
author:  CACHET Team <cph.cachet@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0' 

dependencies:
  flutter:
    sdk: flutter
  background_locator_2:
#    git:
#      url: https://github.com/hieudz/background_locator_fixed

dependency_overrides:
  background_locator_2:
    git:
      url: https://github.com/Yukams/background_locator_fixed
#      ref: 652fc025ca0d39d43afa62e2aacef64aa5f6a147
#      url: https://github.com/hieudz/background_locator_fixed
#      ref: bbe07e6a1308350c820753419625a9b1e544e128

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:

